version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: test_oauth2
    restart: always
    environment:
      MYSQL_DATABASE: spring_session
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - "3311:3306"

    volumes:
      # Persist MySQL data
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]


volumes:
  mysql-data: