logging:
    file:
        name: ./log/application.log
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE
                web:
                    filter:
                        CommonsRequestLoggingFilter: DEBUG
application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000
            refresh-token:
                expiration: 604800000

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        stomp:
            relay:
                host: localhost
                port: 61613
                login: guest
                passcode: guest
    data:
        redis:
            database: 1
            host: localhost
            port: 6379
    datasource:
        password: app
        tomcat:
            max-active: 50
            max-wait: 10000
            test-on-borrow: true
        url: jdbc:mysql://localhost:3311/spring_session
        username: app
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 1043134925846-mr1149hliaqo89g01f7j1si83n5n06kc.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                            - email
                            - profile
                    facebook:
                        client-id: 3514442532032319
                        client-secret: 5928175fb97f99e83a0aab3ed44a8e66
                        scope:
                            - email
                            - public_profile
                    github:
                        client-id: Ov23li59Ul4OYexo7LiS
                        client-secret: 83dcb4d511f4429cccb7e361a9a164f4683191f1
                        scope:
                            - read:user
                            - user:email

                provider:
                    facebook:
                        user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
                    github:
                        user-name-attribute: login



---
spring.config.activate.on-profile: local
---
spring.config.activate.on-profile: docker-compose
spring:
    datasource:
        url: 'jdbc:mysql://mysql/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
        username: app
        password: app
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    data:
        redis:
            host: redis
            port: 6379